### ISSUE TITLE
subprogram won't work

### ISSUE THREAD

**Issue by bliblubli** [JacquesLucke/animation_nodes#867]
Hi,
for some reason, I can't use subprograms in AN on latest Blender. I compiled both Blender and AN with the same python version and get this error:
```
.config/blender/2.79/scripts/addons/animation_nodes/execution/main_execution_unit.py", line 38, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'NodeTree'", line 29, in <module>
  File "group: 'My Loop'", line 30, in main
AttributeError: 'RNA_Types' object has no attribute 'an_VectorListSocket'
Info: Total files 0 | Changed 0 | Failed 0

```
here is a simple file to reproduce: http://pasteall.org/blend/index.php?id=49004

**Comment by bliblubli** [comment]
also note that in the doc http://animation-nodes-manual.readthedocs.io/en/latest/user_guide/subprograms/loop.html it's possible to have ints and floats as loop output, but building latest master, I can't get it.

**Comment by bliblubli** [comment]
It works in official 2.0a, only latest master has the bug in post 1. However, loop output still only has vector and condition as output, I can't find a way to get float and/or int.

**Comment by JacquesLucke** [comment]
ok, will check what causes the problem in the master branch. What Blender version are you using?

You can click on the "New Generator Output" to create a new output for the loop.

**Comment by bliblubli** [comment]
@JacquesLucke I was using latest master of Blender (so 2.79.2 currently).
I clicked on advanced node settings -> change type. Is that what you mean? All "loop generator outputs" nodes have vectors as default input and I couldn't find a button to add another output beside "condition" which can be made visible (hidden by default).
![change loop type](https://user-images.githubusercontent.com/29454545/36630940-728408e8-196f-11e8-8cd6-1b5f12021cc5.png)
How are your studies and your finances going?

**Comment by JacquesLucke** [comment]
AN might not be compatible with blenders master version (buildbot builds), it will be compatible with 2.79a though.

Every loop output gets its own loop generator output node. Maybe this is why you are confused.

When you click on "New Generator Output" it *should* show a search box where you can choose the type. Is that not the case for you? If not, can you make a gif showing that it does not show the search box?

studies are going well, the semester is almost over for me. Next week I have 3 exams and have to hand in a larger homework, so it will be quite stressful. Then I will be not at home for some days and then I'll have more time for my personal projects like AN again :)
Finances are going well, patreon and my scholarship really help a lot.

**Comment by bliblubli** [comment]
ok, found it, it is on the input node, thank you. I usually add all my nodes with ctrl+A to search for keywords. Wouldn't it be better to have the + to add new outputs on the loop output node? Or at least on both as one may look for it there?

Take it easy with your big homework. Stress control is a key component in your job later, so it may also  be good to train yourself now, to find the right balance. I'm pretty sure you will get a good job anyway :)

**Comment by JacquesLucke** [comment]
I could do it like that but currently I prefer it the way it is. Having multiple nodes for outputs makes it easier to use the condition socket + it can make your loop easier to "read". 
Maybe I'll even remove this node from the search. It is connected to the loop, so maybe it should be created in the loop..

no worries, I think I'm quite good at finding the right balance. :D
Thanks :)

**Comment by MasterJames** [comment]
The iterators don't seem to work properly?
I have the example of placing Spheres on a Cube's Corners with both a second iterator and as a parameter list object to get the element by name manually. Neither of them seem to work.
You can connect manually the manual as parameter version.
Alas you only get one first copy on the first corner.
[SpheresOnCorners-01.zip](https://github.com/JacquesLucke/animation_nodes/files/1780491/SpheresOnCorners-01.zip)

**Comment by bliblubli** [comment]
@JacquesLucke would it be possible to still fix the bug in first post (latest AN master with latest Blender Master)?

**Comment by JacquesLucke** [comment]
ah yes, sry. Will check that tomorrow or so.
