### ISSUE TITLE
an 2.1 for python 3.6 removes all the nodes connections in existing trees

### ISSUE THREAD

**Issue by mirlip** [JacquesLucke/animation_nodes#891]
Hi,
thanks for all the updated binaries. For some reason, when I try to open files made with 2.0a, all the links are removed. In huge trees it's a lot of work. Would it be possible to keep the links?

**Comment by JacquesLucke** [comment]
in general node trees that have been created in earlier versions don't work in new versions of AN.

AN should not remove all links though, not sure what causes that, can you send me the file (or a simplified version of it)?
However sometimes it might be easier to just rebuild the tree instead of trying to fix things here and there because some things are supposed to be done  differently in newer versions.

**Comment by mirlip** [comment]
http://pasteall.org/blend/index.php?id=49269

**Comment by mirlip** [comment]
usually, even starting with a blender where AN was not present wouldn't remove the links and all the broken nodes would work again as soon as AN was activated in user pref. It's the first time I see all the connections removed. And in this case, that's a huge tree. Of course, replacing some broken nodes is ok and I find it good you work on better AN than use time for compatibility stuff. I'll have a look if the broken links could come from Blender too.

**Comment by mirlip** [comment]
ok, it doesn't work in 2.79b either, so shouldn't come from a breakage in master. Here is a part of the error:
```
File "/home/testing/source/2.79b/2.79/scripts/addons/animation_nodes/tree_info/forest_data.py", line 72, in insertNodes
    dataTypeBySocket[socketID] = socket.dataType
AttributeError: 'NodeSocket' object has no attribute 'dataType'
```

**Comment by JacquesLucke** [comment]
The fact that all links are removed is definitely a bug in AN. AN does some things to make slightly different versions compatible but that does not work in some cases. (e.g. AN can easily handle it when the order of sockets in a node changes between versions)

For that AN removes all links and tries to recreate them one by one. It looks like there is a bug in that procedure. Will check the file a bit later today.

**Comment by mirlip** [comment]
ok, thanks :)

**Comment by JacquesLucke** [comment]
I think I fixed the main problem here.
Will upload new v2.1 test builds very soon.

**Comment by mirlip** [comment]
thank you

**Comment by JacquesLucke** [comment]
the new builds are up now: https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.1_testbuilds

**Comment by mirlip** [comment]
awesome, works pretty good. only the invoke subprogram nodes were deconnected, but they had a combine mesh data node, which got broken between 2.0a and 2.1, so I guess that was the reason of the deconnection and it was fast to do it manually. So thanks a lot :)
