### ISSUE TITLE
animation nodes for python 3.10

### ISSUE THREAD

**Issue by luckychris** [JacquesLucke/animation_nodes#1826]
![image](https://user-images.githubusercontent.com/232549/151789821-ad2c8b25-98a9-47b7-b6d1-36737f6841f7.png)

can please somebody create a build of animation nodes version with python 3.9.10?

**Comment by luckychris** [comment]
i tried to compile it on my own, but i got this error:

/Users/chris/Downloads/animation_nodes-master/animation_nodes/nodes/vector/vector_math.c:12089:61: error: implicit declaration of function '__Pyx_RaiseUnexpectedTypeError' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    if (!(likely(PyDict_CheckExact(o))||((o) == Py_None) || __Pyx_RaiseUnexpectedTypeError("dict", o))) __PYX_ERR(0, 86, __pyx_L2_error);
                                                            ^
/Users/chris/Downloads/animation_nodes-master/animation_nodes/nodes/vector/vector_math.c:12089:61: note: did you mean '__Pyx_RaiseNoneNotIterableError'?
/Users/chris/Downloads/animation_nodes-master/animation_nodes/nodes/vector/vector_math.c:4578:27: note: '__Pyx_RaiseNoneNotIterableError' declared here
static CYTHON_INLINE void __Pyx_RaiseNoneNotIterableError(void);

**Comment by harisreedhar** [comment]
@luckychris What OS are you using? Is blender updated to python 3.10.x?

**Comment by luckychris** [comment]
oh, sorry:

![image](https://user-images.githubusercontent.com/232549/151813249-1e73c58c-62ff-44b8-8787-0426eef26604.png)

**Comment by luckychris** [comment]
Blender 3.1 and Blender 3.2

**Comment by harisreedhar** [comment]
I think you have to build yourself for m1 mac. 
For linux this is the procedure i use. It was working fine for blender 3.2
````
git clone https://github.com/JacquesLucke/animation_nodes
cd animation_nodes
conda create -n anenv python=3.9 cython numpy
conda activate anenv
python setup.py build --export --noversioncheck
````

**Comment by luckychris** [comment]
thank you very much for your instruction. In the last step i got:

/Users/chris/Downloads/animation_nodes-master/animation_nodes/nodes/vector/vector_math.c:12089:61: error: implicit declaration of function '__Pyx_RaiseUnexpectedTypeError' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    if (!(likely(PyDict_CheckExact(o))||((o) == Py_None) || __Pyx_RaiseUnexpectedTypeError("dict", o))) __PYX_ERR(0, 86, __pyx_L2_error);
                                                            ^
/Users/chris/Downloads/animation_nodes-master/animation_nodes/nodes/vector/vector_math.c:12089:61: note: did you mean '__Pyx_RaiseNoneNotIterableError'?
/Users/chris/Downloads/animation_nodes-master/animation_nodes/nodes/vector/vector_math.c:4578:27: note: '__Pyx_RaiseNoneNotIterableError' declared here
static CYTHON_INLINE void __Pyx_RaiseNoneNotIterableError(void);

**Comment by OmarEmaraDev** [comment]
What version of Cython did you install? We build using `0.29`, so it could be that you are using a higher version.
We now daily build for 3.10 3f16a29. But as mentioned above, Github doesn't support Mac ARM runners at the moment, so you will have to compile that on your own.

**Comment by luckychris** [comment]
Cython version 0.29.25

**Comment by OmarEmaraDev** [comment]
Are you sure it is that version? Because that symbol was only added in the 3.0 release in https://github.com/cython/cython/pull/3693.

**Comment by luckychris** [comment]
yes, i think so...here is a screenshot

![image](https://user-images.githubusercontent.com/232549/151924383-bc832a62-1785-43da-87e4-d467721d303e.png)

**Comment by meikasahara** [comment]
When attempting to build on linux (Ubuntu 20.04.3 LTS) I get the following error:

error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

Note: python3.10-dev is already installed.
A similar error appears when attempting to compile through a python 3.10 conda environment.

**Comment by OmarEmaraDev** [comment]
@luckychris What is the first line in `animation_nodes/animation_nodes/nodes/vector/vector_math.c`?

@meikasahara Can you attach the full error log?

**Comment by meikasahara** [comment]
These are the compile messages after the command
`python setup.py build --export --noversioncheck`

[error_compile_log.txt](https://github.com/JacquesLucke/animation_nodes/files/7980796/error_compile_log.txt)

**Comment by luckychris** [comment]
ok, i found out, that it took the "old" python version and the right command should be:

python3.10 setup.py build --export --noversioncheck

unfortunately than i got this:
Cython is not installed for this Python version.

although i downloaded the latest cython version. Do you have any hint for me?

**Comment by luckychris** [comment]
ok, after deinstalling cython and installing again, i made it, that it compiles....but with this error now:


/Users/chris/Downloads/animation_nodes-master/animation_nodes/nodes/vector/vector_math.c:12089:61: error: implicit declaration of function '__Pyx_RaiseUnexpectedTypeError' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    if (!(likely(PyDict_CheckExact(o))||((o) == Py_None) || __Pyx_RaiseUnexpectedTypeError("dict", o))) __PYX_ERR(0, 86, __pyx_L2_error);
                                                            ^
/Users/chris/Downloads/animation_nodes-master/animation_nodes/nodes/vector/vector_math.c:12089:61: note: did you mean '__Pyx_RaiseNoneNotIterableError'?
/Users/chris/Downloads/animation_nodes-master/animation_nodes/nodes/vector/vector_math.c:4578:27: note: '__Pyx_RaiseNoneNotIterableError' declared here
static CYTHON_INLINE void __Pyx_RaiseNoneNotIterableError(void);
                          ^
1 error generated.
error: command '/usr/bin/clang' failed with exit code 1
(base) chris@MBPvonChristoph animation_nodes-master %

**Comment by luckychris** [comment]
OMG...i made it. with the newest cython and the newest animation nodes download...it finally worked. sorry for bothering you.

**Comment by mikeew** [comment]
@luckychris I'm running a similar setup:
Apple Silicon M1
MacOS Monterey 10.2.1
Blender 3.1 (and 3.2) for M1
Python 3.10
Cython 0.29.28
Animation Nodes 2.3

I've run the following commands:

```
git clone https://github.com/JacquesLucke/animation_nodes
cd animation_nodes
conda create -n anenv python=3.10 cython numpy
conda activate anenv
python setup.py build --export --noversioncheck
```

All commands complete successfully (apart from a few warnings)

When I install the created zip file and enable the add-on I get the following error:

> This build does not work at the moment.

Any ideas? Can you upload your zip file?


Warnings that I get:
/animation_nodes/data_structures/lists/utils.c:1669:7: warning: variable '__pyx_v_newStart' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]

/animation_nodes/data_structures/meshes/validate.c:7804:13: warning: code will never be executed [-Wunreachable-code]
  __pyx_r = 0;

/animation_nodes/nodes/rotation/c_utils.o -g0
/Users/mana/Downloads/Mikee/animation_nodes/animation_nodes/nodes/rotation/c_utils.c:9742:5: warning: code will never be executed [-Wunreachable-code]
    PyErr_SetString(PyExc_ZeroDivisionError, "float division");

/animation_nodes/nodes/matrix/distribute_matrices.c:8766:7: warning: variable '__pyx_v_xDis' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
  if (__pyx_t_3) {

**Comment by OmarEmaraDev** [comment]
@mikeew Those seems like harmless warnings, there is probably an actual error somewhere, can you try to find it and attach it here?

**Comment by mikeew** [comment]
> @mikeew Those seems like harmless warnings, there is probably an actual error somewhere, can you try to find it and attach it here?

The only error text I could find is encapsulated in a warning, I've attached the whole compile process as I'm not sure what is going on. Appreciate your help!

[animation_nodes.txt](https://github.com/JacquesLucke/animation_nodes/files/8103956/animation_nodes.txt)

**Comment by OmarEmaraDev** [comment]
@mikeew The log seems okay. Does it prints any trace when saying "This build does not work at the moment."?

**Comment by luckychris** [comment]
@mikeew : First i have to say i am not an expert with cython and compiling things....i just made it work for me.

i just this command:

python3.10 setup.py build --export --noversioncheck

and this worked for me after i installed the newest cython version and downloaded the newest version of animation nodes from here. i will append my zip file, hopefully it works for you too.

**Comment by luckychris** [comment]
just if someone is interested in using animation nodes for newest Blender versions on Macos:

I made a github with my compiled versions, which you can download here: 
https://github.com/luckychris/compiled_animation_nodes
