### ISSUE TITLE
Animation Nodes doesn't work with 2.8.69

### ISSUE THREAD

**Issue by dimitripaiva** [JacquesLucke/animation_nodes#1100]
Hello, 
until the 2.8.61 build AN was working fine, but then I downloaded the newest 2.8 beta and AN is simply broken. Even basic operations like Object Transform Output doesn't work. Please, see the image. Could you please take a look? 

![image](https://user-images.githubusercontent.com/50772360/57970317-2e278100-7956-11e9-8d9b-5e55a20188af.png)

**Comment by 3DSinghVFX** [comment]
Did try the latest AN version?

**Comment by OmarSquircleArt** [comment]
Please press on *Toggle Console* in the problems panel and copy the contents of the console here.

**Comment by dimitripaiva** [comment]
> Did you try the latest AN version?

Yeah, I'm using 2.8.69.

**Comment by dimitripaiva** [comment]
> Please press on _Toggle Console_ in the problems panel and copy the contents of the console here.

    scene.update()
AttributeError: 'Scene' object has no attribute 'update'






Traceback (most recent call last):
  File "C:\Users\conta\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\execution\units.py", line 58, in setupExecutionUnits
    unit.setup()
  File "C:\Users\conta\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 26, in setup
    exec(self.setupCodeObject, self.executionData, self.executionData)
  File "setup: 'NodeTree'", line 10, in <module>
KeyError: 'bpy_prop_collection[key]: key "Object Transforms Output" not found'
Traceback (most recent call last):
  File "C:\Users\conta\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\operators\execute_tree.py", line 21, in execute
    nodeTree.execute()
  File "C:\Users\conta\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\base_types\node_tree.py", line 91, in execute
    self._execute()
  File "C:\Users\conta\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\base_types\node_tree.py", line 104, in _execute
    success = unit.execute()
  File "C:\Users\conta\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 73, in raiseNotSetupException
    raise ExecutionUnitNotSetup()
animation_nodes.problems.ExecutionUnitNotSetup

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by OmarSquircleArt** [comment]
Thanks for the report! This was already fixed in 0872685. Newer builds should work.
